issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable-all: true
  disable:
    - godox
    - nlreturn
    - exhaustruct
    - depguard
    - gofmt  # gofumpt still enabled
    - goimports  # conflicts with gofumpt
    # deprecated
    - ifshort
    - deadcode
    - varcheck
    - interfacer
    - exhaustivestruct
    - scopelint
    - golint
    - structcheck
    - nosnakecase
    - maligned
linters-settings:
  varnamelen:
    ignore-names:
      - id
      - db
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
